version: "3"
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: server
    depends_on:
      - mongo
    environment:
      - NODE_DB_URI=mongodb://mongo/habitica # this only needs to be adapted if using a separate database
      - BASE_URL=http://127.0.0.1:8080 # change this to the URL under which your instance will be reachable
      - INVITE_ONLY=false # change to `true` after registration of initial users, to restrict further registrations
    networks:
      - habitica
    ports:
      - "3000:3000"
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: client
    depends_on:
      - server
    networks:
      - habitica
    ports:
      - "8080:80"
  mongo:
    image: docker.io/mongo:5.0
    restart: unless-stopped
    command: ["--replSet", "rs", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate() }" | mongosh --port 27017 --quiet
      interval: 10s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    networks:
      - habitica
    ports:
      - "27017:27017"
networks:
  habitica:
    driver: bridge
